"""Two editable views of the same seven-stage workshop flow.

Native OpenROAD images are generated by render_stages.py from saved .odb files.
The first slide groups the stages by day; the second shows files and the engine.
"""
from pathlib import Path
import base64, html, subprocess
import xml.etree.ElementTree as ET
P=Path(__file__).resolve().parent; A=P/'images'
B,D,G,U='#5E81AC','#4C566A','#A3BE8C','#B48EAD'
STAGES=[('floorplan',['Floorplanning'],'#EBCB8B'),
        ('global_placement',['Global','placement'],'#81A1C1'),
        ('detailed_placement',['Detailed','placement'],'#81A1C1'),
        ('cts',['Clock-tree','synthesis'],'#8FBCBB'),
        ('global_routing',['Global','routing'],'#D08770'),
        ('detailed_routing',['Detailed','routing'],'#D08770'),
        ('finishing',['Finishing'],'#B48EAD')]

def text(x,y,value,size=25,c=D,anchor='start',mono=False):
    font='DejaVu Sans Mono' if mono else 'Latin Modern Sans,sans-serif'
    return f'<text x="{x}" y="{y}" fill="{c}" font-family="{font}" font-size="{size}" text-anchor="{anchor}">{html.escape(value)}</text>'
def line(x,y,X,Y,arrow=False,dash=False):
    return f'<path d="M{x},{y} L{X},{Y}" stroke="{B}" stroke-width="2.5" fill="none"'+(' marker-end="url(#a)"' if arrow else '')+(' stroke-dasharray="4 7"' if dash else '')+'/>'
def image(path,x,y,w,h):
    if path.suffix=='.svg':
        # Inline vector artwork: an SVG embedded as <image> is rasterized by
        # librsvg at its small display size when exporting the overview PDF.
        ET.register_namespace('', 'http://www.w3.org/2000/svg')
        root=ET.fromstring(path.read_text())
        root.attrib.update(x=str(x),y=str(y),width=str(w),height=str(h),
                           preserveAspectRatio='xMidYMid meet')
        return ET.tostring(root,encoding='unicode')
    kind='image/png'
    data=base64.b64encode(path.read_bytes()).decode()
    return f'<image x="{x}" y="{y}" width="{w}" height="{h}" preserveAspectRatio="xMidYMid meet" href="data:{kind};base64,{data}"/>'
def canvas():
    return ['<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="760" viewBox="0 0 1800 760"><defs><marker id="a" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="'+B+'"/></marker></defs><rect width="1800" height="760" fill="white"/>']
def save(name,s):
    p=A/f'{name}.svg';p.write_text('\n'.join(s+['</svg>']))
    subprocess.run(['rsvg-convert','-f','pdf','-o',str(p.with_suffix('.pdf')),str(p)],check=True)
def stage(i,x,y,w=180,h=210,label_y=525,label_h=78):
    name,labels,color=STAGES[i]
    suffix='svg' if name in ['floorplan','global_placement','detailed_placement','cts'] else 'png'
    filename='finishing_klayout.png' if name=='finishing' else f'{name}.{suffix}'
    directories={'floorplan':'placement','global_placement':'placement',
                 'detailed_placement':'placement','cts':'routing',
                 'global_routing':'routing','detailed_routing':'routing',
                 'finishing':'finishing'}
    out=[image(A/directories[name]/filename,x,y,w,h)]
    out.append(f'<rect x="{x}" y="{label_y}" width="{w}" height="{label_h}" fill="{color}" stroke="{B}" stroke-width="1.5"/>')
    for j,t in enumerate(labels):
        yy=label_y+label_h/2+8 if len(labels)==1 else label_y+label_h/2-8+j*28
        out.append(text(x+w/2,yy,t,24,'#2E3440','middle'))
    return out

def file_icon(x,y,w,h,lines,title=None):
    fold=22
    out=[f'<path d="M{x},{y} H{x+w-fold} L{x+w},{y+fold} V{y+h} H{x} Z M{x+w-fold},{y} V{y+fold} H{x+w}" fill="#F4F6F8" stroke="{B}" stroke-width="2"/>']
    if title:out.append(text(x+12,y+31,title,22,B))
    start=y+58 if title else y+(h-len(lines)*27)/2+22
    for i,t in enumerate(lines):out.append(text(x+12,start+i*27,t,21,D,mono=True))
    return out

# Eight equally spaced blocks: the input bundle, followed by seven flow stages.
s=canvas()
positions=[30+i*220 for i in range(8)]
for x,X,day in [(30,430,'Day 1'),(470,1090,'Day 2'),(1130,1750,'Day 3')]:
    s += [text((x+X)/2,110,day,38,B,'middle'),line(x,140,X,140)]
# A small stack of file icons above the new input block.
for x,y in [(52,264),(70,280),(88,296)]:
    s += file_icon(x,y,98,125,[])
    for yy in [y+47,y+67,y+87]:s += [line(x+16,yy,x+72,yy)]
s.append(f'<rect x="30" y="495" width="180" height="104" fill="#ECEFF4" stroke="{B}" stroke-width="1.5"/>')
for j,label in enumerate(['Cell library','Design files','Flow script']):
    s += [text(120,525+29*j,label,24,D,'middle')]
for i,x in enumerate(positions[1:]):
    s += stage(i,x,220,w=180,h=230,label_y=495,label_h=104)
for x,X in zip(positions,positions[1:]):
    s += [line(x+183,547,X-10,547,True)]
save('workshop-schedule',s)

# The same stages as an engine: no schedule and no command-level explanation.
s=canvas()
s.append('<g transform="translate(0,-40)">')
# File bundle at left. Cell GDS/SPICE are introduced later as source views;
# this overview lists the library abstractions supplied to the P&R engine.
s += file_icon(15,195,193,175,['cells.v','cells.lef','tech.lef','cells.lib'],'Cell library')
s += file_icon(15,393,193,79,['design.v'])
s += file_icon(15,518,193,96,['flow.tcl','flow.py'])
s.append(f'<rect x="255" y="190" width="1300" height="453" rx="8" fill="none" stroke="{B}" stroke-width="3" stroke-dasharray="5 8"/>')
s += [text(280,247,'Physical implementation',31,B),text(1400,246,'i.e. OpenROAD',31,B,'end'),image(A/'openroad-logo.svg',1430,208,70,70)]
positions=[278+i*181 for i in range(7)]
for i,x in enumerate(positions):
    s += stage(i,x,301,w=162,h=210,label_y=536)
    if i<6:s += [line(x+164,575,positions[i+1]-7,575,True)]
# Library, design and flow scripts join before the first stage.
s.append(f'<path d="M208,282 H233 V575 H268 M208,432 H233 M208,566 H233" fill="none" stroke="{B}" stroke-width="2.5"/>')
s += [line(246,575,273,575,True)]
s += file_icon(1621,523,168,104,['design.v','design.def'])
s += [line(1555,575,1614,575,True)]
s.append('</g>')
save('workshop-flow',s)
